export default () => ({
  type: 'sn-scatter-plot',
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: 'VhcvfgJ',
          qType: 'sn-scatter-plot',
        },
        qMeta: {
          privileges: ['read', 'update', 'delete', 'exportdata'],
        },
        qSelectionInfo: {},
        qHyperCube: {
          qSize: {
            qcx: 3,
            qcy: 6,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: 'Country',
              qApprMaxGlyphCount: 7,
              qCardinal: 6,
              qSortIndicator: 'A',
              qGroupFallbackTitles: ['Country'],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 6,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ['$ascii', '$text', '$geoname', '$relates_CarsDataSet.Country_GeoInfo'],
              qDimensionType: 'D',
              qGrouping: 'N',
              qNumFormat: {
                qType: 'R',
                qnDec: 14,
                qUseThou: 1,
                qFmt: '##############',
                qDec: ',',
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ['Country'],
              qMin: 'NaN',
              qMax: 'NaN',
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 6,
                qHypercubeCardinal: 6,
                qAllValuesCardinal: -1,
              },
              qLibraryId: 'ZPkzL',
              title: 'Country',
              coloring: {
                changeHash: '0.7120835032460346',
                baseColor: {
                  color: '#f93f17',
                  index: 10,
                },
                colorMapRef: 'ZPkzL',
              },
              autoSort: true,
              cId: 'VRmDs',
              othersLabel: 'Others',
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: 'Avg Horsepower',
              qApprMaxGlyphCount: 5,
              qCardinal: 0,
              qSortIndicator: 'D',
              qNumFormat: {
                qType: 'R',
                qnDec: 0,
                qUseThou: 0,
                qFmt: '########',
                qDec: ',',
                qThou: ' ',
              },
              qMin: 69,
              qMax: 106.5,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: 'tfqVUAV',
              qTrendLines: [],
              coloring: {},
              autoSort: true,
              cId: 'rjzPp',
              numFormatFromTemplate: true,
            },
            {
              qFallbackTitle: 'Avg Miles Per Gallon',
              qApprMaxGlyphCount: 5,
              qCardinal: 0,
              qSortIndicator: 'D',
              qNumFormat: {
                qType: 'R',
                qnDec: 0,
                qUseThou: 0,
                qFmt: '########',
                qDec: ',',
                qThou: ' ',
              },
              qMin: 24.85,
              qMax: 37.3,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: 'AhjdKx',
              qTrendLines: [],
              coloring: {},
              autoSort: true,
              cId: 'kZmNKB',
              numFormatFromTemplate: true,
            },
          ],
          qEffectiveInterColumnSortOrder: [2, 1, 0],
          qGrandTotalRow: [
            {
              qText: '89,954545',
              qNum: 89.95454545454545,
              qElemNumber: -1,
              qState: 'X',
              qIsTotalCell: true,
            },
            {
              qText: '28,799242',
              qNum: 28.799242424242422,
              qElemNumber: -1,
              qState: 'X',
              qIsTotalCell: true,
            },
          ],
          qDataPages: [],
          qPivotDataPages: [],
          qStackedDataPages: [],
          qMode: 'S',
          qNoOfLeftDims: -1,
          qTreeNodesOnDim: [],
          qColumnOrder: [],
        },
        refLine: {
          refLinesX: [],
          refLinesY: [],
        },
        showTitles: true,
        title: '',
        subtitle: '',
        footnote: '',
        disableNavMenu: false,
        showDetails: false,
        showDisclaimer: true,
        navigation: false,
        dataPoint: {
          bubbleSizes: 5,
          rangeBubbleSizes: [2, 8],
        },
        labels: {
          mode: 1,
        },
        compressionResolution: 5,
        gridLine: {
          auto: true,
          spacing: 2,
        },
        color: {
          auto: true,
          mode: 'primary',
          formatting: {
            numFormatFromTemplate: true,
          },
          useBaseColors: 'off',
          paletteColor: {
            index: 6,
          },
          useDimColVal: true,
          useMeasureGradient: true,
          persistent: false,
          expressionIsColor: true,
          expressionLabel: '',
          measureScheme: 'sg',
          reverseScheme: false,
          dimensionScheme: '12',
          autoMinMax: true,
          measureMin: 0,
          measureMax: 10,
        },
        legend: {
          show: true,
          dock: 'auto',
          showTitle: true,
        },
        xAxis: {
          show: 'all',
          dock: 'near',
          spacing: 1,
          autoMinMax: true,
          minMax: 'min',
          min: 0,
          max: 10,
        },
        yAxis: {
          show: 'all',
          dock: 'near',
          spacing: 1,
          autoMinMax: true,
          minMax: 'min',
          min: 0,
          max: 10,
        },
        tooltip: {
          auto: true,
          hideBasic: false,
          title: '',
          description: '',
        },
        visualization: 'sn-scatter-plot',
        version: '2.0.0',
        extensionMeta: {
          translationKey: '',
          icon: 'puzzle',
          iconChar: 'puzzle',
          isLibraryItem: true,
          visible: true,
          name: 'sn-scatter-plot',
          description: 'A scatter plot.',
          template: 'sn-scatter-plot',
          iconPath:
            'M14.5,9 L13,9 L13,3.3 C13,3.1 12.9,3 12.7,3 L8,3 L8,1.5 C8,0.7 7.3,0 6.5,0 C5.7,0 5,0.7 5,1.5 L5,3 L0.3,3 C0.1,3 0,3.1 0,3.3 L0,9 L1.5,9 C2.3,9 3,9.7 3,10.5 C3,11.3 2.3,12 1.5,12 L0,12 L0,15.7 C0,15.9 0.1,16 0.3,16 L5,16 L5,14.5 C5,13.7 5.7,13 6.5,13 C7.3,13 8,13.7 8,14.5 L8,16 L12.7,16 C12.9,16 13,15.9 13,15.7 L13,12 L14.5,12 C15.3,12 16,11.3 16,10.5 C16,9.7 15.3,9 14.5,9 Z',
          isThirdParty: true,
          version: '2.0.0',
          author: 'QlikTech International AB',
          type: 'visualization',
          supernova: true,
        },
      },
      getHyperCubeData: [
        {
          qMatrix: [
            [
              {
                qText: 'Italy',
                qNum: 'NaN',
                qElemNumber: 5,
                qState: 'O',
              },
              {
                qText: '69',
                qNum: 69,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: '37,3',
                qNum: 37.3,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: 'Japan',
                qNum: 'NaN',
                qElemNumber: 1,
                qState: 'O',
              },
              {
                qText: '78,685714',
                qNum: 78.68571428571428,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: '33,842857',
                qNum: 33.84285714285715,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: 'Germany',
                qNum: 'NaN',
                qElemNumber: 0,
                qState: 'O',
              },
              {
                qText: '76,6',
                qNum: 76.6,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: '31,705',
                qNum: 31.704999999999995,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: 'France',
                qNum: 'NaN',
                qElemNumber: 4,
                qState: 'O',
              },
              {
                qText: '89',
                qNum: 89,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: '29,38',
                qNum: 29.380000000000003,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: 'USA',
                qNum: 'NaN',
                qElemNumber: 2,
                qState: 'O',
              },
              {
                qText: '99,223881',
                qNum: 99.22388059701493,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: '25,362687',
                qNum: 25.36268656716418,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
            [
              {
                qText: 'Sweden',
                qNum: 'NaN',
                qElemNumber: 3,
                qState: 'O',
              },
              {
                qText: '106,5',
                qNum: 106.5,
                qElemNumber: 0,
                qState: 'L',
              },
              {
                qText: '24,85',
                qNum: 24.85,
                qElemNumber: 0,
                qState: 'L',
              },
            ],
          ],
          qTails: [
            {
              qUp: 0,
              qDown: 0,
            },
          ],
          qArea: {
            qLeft: 0,
            qTop: 0,
            qWidth: 3,
            qHeight: 6,
          },
        },
      ],
      getEffectiveProperties: {},
    },
  ],
});
