export default () => ({
  type: 'sn-scatter-plot',
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: 'afcfb91d-ddac-4af6-8833-2c024b58649a',
          qType: 'embeddedsnapshot',
        },
        qMeta: {
          privileges: ['read', 'update', 'delete', 'exportdata', 'approve'],
          title: '',
          description: '',
          annotation: '',
        },
        qBookmark: {
          qStateData: [
            {
              qStateName: '$',
              qFieldItems: [],
            },
            {
              qStateName: 'state 1',
              qFieldItems: [],
            },
            {
              qStateName: 'state 2',
              qFieldItems: [],
            },
          ],
          qUtcModifyTime: 44595.44673611111,
          qVariableItems: [],
          qPatches: [],
        },
        qFieldInfos: [],
        creationDate: '2022-02-03T09:43:19.585Z',
        qMeta: {
          privileges: ['read', 'update', 'delete', 'exportdata'],
        },
        qSelectionInfo: {},
        qHyperCube: {
          qSize: {
            qcx: 3,
            qcy: 7942,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: 'A Product (1)',
              qApprMaxGlyphCount: 48,
              qCardinal: 7942,
              qSortIndicator: 'A',
              qGroupFallbackTitles: ['A Product (1)'],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 0,
                qOption: 7942,
                qDeselected: 0,
                qAlternative: 0,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ['$key', '$ascii', '$text'],
              qDimensionType: 'D',
              qGrouping: 'N',
              qNumFormat: {
                qType: 'U',
                qnDec: 0,
                qUseThou: 0,
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ['Line Desc 1'],
              qMin: 'NaN',
              qMax: 'NaN',
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 7942,
                qHypercubeCardinal: 7942,
                qAllValuesCardinal: -1,
              },
              qLibraryId: '71ee0359-1f6a-4332-9f67-521673cec677',
              title: 'A Product (1)',
              coloring: {
                colorMapRef: '71ee0359-1f6a-4332-9f67-521673cec677',
                changeHash: '0.954331662462419',
              },
              autoSort: true,
              cId: 'Tbme',
              othersLabel: 'Others',
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: 'Actual Amount',
              qApprMaxGlyphCount: 11,
              qCardinal: 0,
              qSortIndicator: 'D',
              qNumFormat: {
                qType: 'U',
                qnDec: 0,
                qUseThou: 0,
              },
              qMin: -849.12,
              qMax: 31027222.339999925,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: 'uQbd',
              qTrendLines: [],
              autoSort: true,
              cId: 'dwhpG',
              numFormatFromTemplate: true,
              quarantine: {
                qNumFormat: {},
                isCustomFormatted: false,
              },
            },
            {
              qFallbackTitle: 'Sales $',
              qApprMaxGlyphCount: 15,
              qCardinal: 0,
              qSortIndicator: 'D',
              qNumFormat: {
                qType: 'U',
                qnDec: 0,
                qUseThou: 0,
              },
              qMin: -20456.23,
              qMax: 5295622.910000008,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qLibraryId: 'FAeJZM',
              qTrendLines: [],
              autoSort: true,
              cId: 'XQgUkYe',
              numFormatFromTemplate: true,
              quarantine: {
                qNumFormat: {},
                isCustomFormatted: false,
              },
            },
          ],
          qEffectiveInterColumnSortOrder: [2, 1, 0],
          qGrandTotalRow: [
            {
              qText: '46258458.11',
              qNum: 46258458.110000014,
              qElemNumber: -1,
              qState: 'X',
              qIsTotalCell: true,
            },
            {
              qText: '98672601.470002',
              qNum: 98672601.47000188,
              qElemNumber: -1,
              qState: 'X',
              qIsTotalCell: true,
            },
          ],
          qDataPages: [],
          qPivotDataPages: [],
          qStackedDataPages: [],
          qMode: 'S',
          qNoOfLeftDims: -1,
          qTreeNodesOnDim: [],
          qColumnOrder: [],
        },
        refLine: {
          refLinesX: [
            {
              show: true,
              label: 'Reference',
              showLabel: true,
              refLineExpr: {
                value: 0,
                label: '0',
              },
              showValue: true,
              paletteColor: {
                index: -1,
                color: '#333333',
              },
              style: {
                lineThickness: 2,
                lineType: '',
              },
              coloredBackground: false,
              cId: 'adJFbx',
            },
          ],
          refLinesY: [
            {
              show: true,
              label: 'Reference',
              showLabel: true,
              refLineExpr: {
                value: 0,
                label: '0',
              },
              showValue: true,
              paletteColor: {
                index: -1,
                color: '#333333',
              },
              style: {
                lineThickness: 2,
                lineType: '',
              },
              coloredBackground: false,
              cId: 'NUcJ',
            },
          ],
        },
        showTitles: true,
        title: '',
        subtitle: '',
        footnote: '',
        disableNavMenu: false,
        showDetails: false,
        showDisclaimer: true,
        navigation: true,
        dataPoint: {
          bubbleSizes: 5,
          rangeBubbleSizes: [2, 8],
        },
        labels: {
          mode: 1,
        },
        compressionResolution: 7,
        gridLine: {
          auto: true,
          spacing: 2,
        },
        color: {
          auto: true,
          mode: 'primary',
          formatting: {
            numFormatFromTemplate: true,
          },
          useBaseColors: 'off',
          paletteColor: {
            index: 6,
          },
          useDimColVal: true,
          useMeasureGradient: true,
          persistent: false,
          expressionIsColor: true,
          expressionLabel: '',
          measureScheme: 'sg',
          reverseScheme: false,
          dimensionScheme: '12',
          autoMinMax: true,
          measureMin: 0,
          measureMax: 10,
        },
        legend: {
          show: true,
          dock: 'auto',
          showTitle: true,
        },
        xAxis: {
          show: 'all',
          dock: 'far',
          spacing: 1,
          autoMinMax: true,
          minMax: 'min',
          min: 0,
          max: 10,
        },
        yAxis: {
          show: 'all',
          dock: 'far',
          spacing: 1,
          autoMinMax: true,
          minMax: 'min',
          min: 0,
          max: 10,
        },
        tooltip: {
          auto: true,
          hideBasic: false,
          chart: {
            style: {
              size: 'medium',
            },
          },
          title: '',
          description: '',
        },
        visualization: 'sn-scatter-plot',
        version: '3.0.0',
        extensionMeta: {
          translationKey: '',
          icon: 'puzzle',
          iconChar: 'puzzle',
          isLibraryItem: true,
          visible: true,
          name: 'sn-scatter-plot',
          description: 'A scatter plot.',
          template: 'sn-scatter-plot',
          iconPath:
            'M14.5,9 L13,9 L13,3.3 C13,3.1 12.9,3 12.7,3 L8,3 L8,1.5 C8,0.7 7.3,0 6.5,0 C5.7,0 5,0.7 5,1.5 L5,3 L0.3,3 C0.1,3 0,3.1 0,3.3 L0,9 L1.5,9 C2.3,9 3,9.7 3,10.5 C3,11.3 2.3,12 1.5,12 L0,12 L0,15.7 C0,15.9 0.1,16 0.3,16 L5,16 L5,14.5 C5,13.7 5.7,13 6.5,13 C7.3,13 8,13.7 8,14.5 L8,16 L12.7,16 C12.9,16 13,15.9 13,15.7 L13,12 L14.5,12 C15.3,12 16,11.3 16,10.5 C16,9.7 15.3,9 14.5,9 Z',
          isThirdParty: true,
          version: '3.0.0',
          author: 'QlikTech International AB',
          type: 'visualization',
          supernova: true,
        },
        snapshotData: {
          object: {
            size: {
              w: 918,
              h: 577,
            },
          },
          rtl: false,
          content: {
            size: {
              w: 917.6000366210938,
              h: 576.6000366210938,
            },
            chartData: {
              xAxisMin: 15613.087781982967,
              xAxisMax: 93738.08778198286,
              yAxisMin: -7168.539690531331,
              yAxisMax: 8456.460309468646,
            },
          },
          parent: {
            h: 641.6,
            w: 937.6,
          },
        },
        dataPages: [
          {
            qMatrix: [
              [
                {
                  qNum: 3805,
                  qElemNumber: 0,
                  qState: 'L',
                },
              ],
              [
                {
                  qText: [-849.12, 309.704141, 59752.58207, -10073.26293],
                  qNum: 3805,
                  qElemNumber: 436904,
                  qState: 'L',
                },
              ],
              [
                {
                  qText: [59752.58207, 309.704141, 120354.284141, -10073.26293],
                  qNum: 651,
                  qElemNumber: 436905,
                  qState: 'L',
                },
              ],
              [
                {
                  qText: [-849.12, 21075.638281, 59752.58207, 10692.671211],
                  qNum: 3,
                  qElemNumber: 436896,
                  qState: 'L',
                },
              ],
              [
                {
                  qText: [59752.58207, 21075.638281, 120354.284141, 10692.671211],
                  qNum: 2,
                  qElemNumber: 436897,
                  qState: 'L',
                },
              ],
              [
                {
                  qText: [-849.12, 10692.671211, 59752.58207, 309.704141],
                  qNum: 24,
                  qElemNumber: 436898,
                  qState: 'L',
                },
              ],
              [
                {
                  qText: [59752.58207, 10692.671211, 120354.284141, 309.704141],
                  qNum: 19,
                  qElemNumber: 436899,
                  qState: 'L',
                },
              ],
            ],
            qTails: [],
            qArea: {
              qLeft: 0,
              qTop: 0,
              qWidth: 3,
              qHeight: 6,
            },
            reformatted: true,
          },
          {
            qMatrix: [],
            qTails: [],
            qArea: {
              qLeft: 0,
              qTop: 0,
              qWidth: 0,
              qHeight: 0,
            },
          },
        ],
        visualizationType: 'sn-scatter-plot',
        sourceObjectId: 'GsqMp',
        sheetId: '31153314-9e26-469c-a8c0-048d038a59c0',
        timestamp: 1643881399581,
        isClone: false,
        supportExport: true,
      },
      getHyperCubeBinnedData: [],
      getEffectiveProperties: {},
    },
  ],
});
