export default () => ({
  type: 'sn-scatter-plot',
  instanceConfig: {
    context: {
      theme: 'theme-global',
    },
  },
  genericObjects: [
    {
      getLayout: {
        qInfo: {
          qId: 'mGFzG',
          qType: 'sn-scatter-plot',
        },
        qMeta: {
          privileges: ['read', 'update', 'delete', 'exportdata'],
        },
        qSelectionInfo: {},
        qHyperCube: {
          qSize: {
            qcx: 3,
            qcy: 10,
          },
          qDimensionInfo: [
            {
              qFallbackTitle: 'Date',
              qApprMaxGlyphCount: 13,
              qCardinal: 36,
              qSortIndicator: 'A',
              qGroupFallbackTitles: ['Date'],
              qGroupPos: 0,
              qStateCounts: {
                qLocked: 0,
                qSelected: 10,
                qOption: 0,
                qDeselected: 0,
                qAlternative: 26,
                qExcluded: 0,
                qSelectedExcluded: 0,
                qLockedExcluded: 0,
              },
              qTags: ['$numeric', '$integer', '$timestamp', '$date'],
              qDimensionType: 'N',
              qGrouping: 'N',
              qNumFormat: {
                qType: 'D',
                qnDec: 0,
                qUseThou: 0,
                qFmt: 'MMMM YYYY',
              },
              qIsAutoFormat: true,
              qGroupFieldDefs: ["=Date(Date#([Date], 'YYYY-MM-DD'), 'MMMM YYYY')"],
              qMin: 42826,
              qMax: 43101,
              qContinuousAxes: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qCardinalities: {
                qCardinal: 36,
                qHypercubeCardinal: 10,
                qAllValuesCardinal: -1,
              },
              qLibraryId: 'UJXJtWv',
              title: 'Date',
              coloring: {
                changeHash: '0.5071487001265802',
              },
              autoSort: true,
              cId: 'hHyJSc',
              othersLabel: 'Others',
              forecast: {
                stepSize: 'days',
              },
            },
          ],
          qMeasureInfo: [
            {
              qFallbackTitle: 'Population',
              qApprMaxGlyphCount: 15,
              qCardinal: 0,
              qSortIndicator: 'D',
              qNumFormat: {
                qType: 'R',
                qnDec: 0,
                qUseThou: 0,
                qFmt: '##############',
                qDec: '.',
                qThou: ',',
              },
              qMin: 21.5,
              qMax: 42.66666666666667,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qTrendLines: [],
              autoSort: true,
              cId: 'NPhdnm',
              numFormatFromTemplate: true,
              forecast: {
                enabled: false,
                method: 'ssa_forecast',
                paletteColor: {
                  index: 0,
                  color: 'none',
                },
                lineThickness: 1,
                lineType: 'dashed',
                lineCurve: 'linear',
                showConfidence: true,
                confidence: 0.95,
              },
            },
            {
              qFallbackTitle: 'Modernity',
              qApprMaxGlyphCount: 10,
              qCardinal: 0,
              qSortIndicator: 'D',
              qNumFormat: {
                qType: 'R',
                qnDec: 0,
                qUseThou: 0,
                qFmt: '########',
                qDec: '.',
                qThou: ',',
              },
              qMin: 0.46499999999999997,
              qMax: 0.6233333333333334,
              qIsAutoFormat: true,
              qAttrExprInfo: [],
              qAttrDimInfo: [],
              qTrendLines: [],
              autoSort: true,
              cId: 'NQJbkxp',
              numFormatFromTemplate: true,
            },
          ],
          qEffectiveInterColumnSortOrder: [2, 1, 0],
          qGrandTotalRow: [
            {
              qText: '29.236842105263',
              qNum: 29.236842105263158,
              qElemNumber: -1,
              qState: 'X',
              qIsTotalCell: true,
            },
            {
              qText: '0.52842105',
              qNum: 0.5284210526315791,
              qElemNumber: -1,
              qState: 'X',
              qIsTotalCell: true,
            },
          ],
          qDataPages: [
            {
              qMatrix: [],
              qTails: [],
              qArea: {
                qLeft: 0,
                qTop: 0,
                qWidth: 0,
                qHeight: 0,
              },
            },
          ],
          qPivotDataPages: [],
          qStackedDataPages: [],
          qMode: 'S',
          qNoOfLeftDims: -1,
          qTreeNodesOnDim: [],
          qColumnOrder: [],
        },
        script: '',
        refLine: {
          refLinesX: [
            {
              show: true,
              label: 'Vertical',
              showLabel: true,
              refLineExpr: {
                value: 15,
                label: '15',
              },
              showValue: true,
              paletteColor: {
                index: -1,
                color: '#fd971f',
              },
              style: {
                lineThickness: 2,
                lineType: '',
              },
              coloredBackground: false,
              cId: 'cYJkqPP',
            },
          ],
          refLinesY: [
            {
              show: true,
              label: 'Horizontal',
              showLabel: true,
              refLineExpr: {
                value: 0.3,
                label: '0.3',
              },
              showValue: true,
              paletteColor: {
                index: -1,
                color: '#fd971f',
              },
              style: {
                lineThickness: 2,
                lineType: '',
              },
              coloredBackground: false,
              cId: 'neQehSV',
            },
            {
              show: true,
              label: '',
              showLabel: true,
              refLineExpr: {
                value: 1,
                label: '1',
              },
              showValue: true,
              paletteColor: {
                index: -1,
                color: '#fd971f',
              },
              style: {
                lineThickness: 2,
                lineType: '',
              },
              coloredBackground: false,
              cId: 'wXXNZf',
            },
          ],
          refLines: [
            {
              show: true,
              label: 'Asd',
              paletteColor: {
                index: -1,
                color: '#fd971f',
              },
              refLineExpr: {
                value: 55,
                label: '55',
              },
              cId: 'PujNJP',
            },
            {
              show: true,
              label: '',
              paletteColor: {
                index: -1,
                color: '#fd971f',
              },
              refLineExpr: {
                value: 90,
                label: '90',
              },
              cId: 'TFKXj',
            },
          ],
          dimRefLines: [],
        },
        trendLines: [],
        showTitles: true,
        title: '',
        subtitle: '',
        footnote: '',
        disableNavMenu: false,
        showDetails: false,
        showDetailsExpression: false,
        showDisclaimer: true,
        navigation: false,
        dataPoint: {
          bubbleSizes: 5,
          rangeBubbleSizes: [2, 8],
          compressionResolution: 5,
          showLabels: true,
          showSegmentLabels: false,
          showTotalLabels: true,
          show: true,
        },
        labels: {
          mode: 1,
        },
        compressionResolution: 5,
        gridLine: {
          auto: false,
          spacing: 3,
        },
        color: {
          auto: true,
          mode: 'primary',
          formatting: {
            numFormatFromTemplate: true,
          },
          useBaseColors: 'off',
          paletteColor: {
            index: 6,
          },
          useDimColVal: true,
          useMeasureGradient: true,
          persistent: false,
          expressionIsColor: true,
          expressionLabel: '',
          measureScheme: 'sg',
          reverseScheme: false,
          dimensionScheme: '12',
          autoMinMax: true,
          measureMin: 0,
          measureMax: 10,
        },
        legend: {
          show: true,
          dock: 'auto',
          showTitle: true,
        },
        xAxis: {
          show: 'all',
          dock: 'near',
          spacing: 1,
          autoMinMax: false,
          minMax: 'min',
          min: 0,
          max: 10,
        },
        yAxis: {
          show: 'all',
          dock: 'near',
          spacing: 1,
          autoMinMax: false,
          minMax: 'min',
          min: 0,
          max: 10,
        },
        tooltip: {
          auto: true,
          hideBasic: false,
          chart: {
            style: {
              size: 'medium',
            },
          },
          title: '',
          description: '',
          data: {},
        },
        visualization: 'sn-scatter-plot',
        version: '1.19.3',
      },
      getHyperCubeData: [
        {
          qMatrix: [
            [
              { qText: 'October 2018', qNum: 43374, qElemNumber: 21, qState: 'O' },
              { qText: '29.25', qNum: 29.25, qElemNumber: 0, qState: 'L' },
              { qText: '0.69', qNum: 0.6900000000000001, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'December 2018', qNum: 43435, qElemNumber: 23, qState: 'O' },
              { qText: '34.75', qNum: 34.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.6825', qNum: 0.6824999999999999, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'November 2018', qNum: 43405, qElemNumber: 22, qState: 'O' },
              { qText: '32', qNum: 32, qElemNumber: 0, qState: 'L' },
              { qText: '0.675', qNum: 0.675, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'September 2018', qNum: 43344, qElemNumber: 20, qState: 'O' },
              { qText: '30.25', qNum: 30.25, qElemNumber: 0, qState: 'L' },
              { qText: '0.6575', qNum: 0.6575, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'July 2018', qNum: 43282, qElemNumber: 18, qState: 'O' },
              { qText: '15', qNum: 15, qElemNumber: 0, qState: 'L' },
              { qText: '0.65', qNum: 0.65, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'August 2017', qNum: 42948, qElemNumber: 7, qState: 'O' },
              { qText: '27.666666666667', qNum: 27.666666666666664, qElemNumber: 0, qState: 'L' },
              { qText: '0.62333333', qNum: 0.6233333333333334, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'February 2019', qNum: 43497, qElemNumber: 25, qState: 'O' },
              { qText: '43', qNum: 43, qElemNumber: 0, qState: 'L' },
              { qText: '0.6175', qNum: 0.6174999999999999, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'February 2017', qNum: 42767, qElemNumber: 1, qState: 'O' },
              { qText: '36', qNum: 36, qElemNumber: 0, qState: 'L' },
              { qText: '0.6125', qNum: 0.6125, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'August 2018', qNum: 43313, qElemNumber: 19, qState: 'O' },
              { qText: '29.75', qNum: 29.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.61', qNum: 0.61, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'January 2017', qNum: 42736, qElemNumber: 0, qState: 'O' },
              { qText: '33.75', qNum: 33.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.605', qNum: 0.605, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'August 2019', qNum: 43678, qElemNumber: 31, qState: 'O' },
              { qText: '45.75', qNum: 45.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.5875', qNum: 0.5874999999999999, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'January 2018', qNum: 43101, qElemNumber: 12, qState: 'O' },
              { qText: '26.75', qNum: 26.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.585', qNum: 0.585, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'December 2017', qNum: 43070, qElemNumber: 11, qState: 'O' },
              { qText: '25.5', qNum: 25.5, qElemNumber: 0, qState: 'L' },
              { qText: '0.5825', qNum: 0.5825, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'January 2019', qNum: 43466, qElemNumber: 24, qState: 'O' },
              { qText: '57.333333333333', qNum: 57.33333333333333, qElemNumber: 0, qState: 'L' },
              { qText: '0.57666667', qNum: 0.5766666666666667, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'February 2018', qNum: 43132, qElemNumber: 13, qState: 'O' },
              { qText: '27.75', qNum: 27.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.5725', qNum: 0.5725, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'March 2017', qNum: 42795, qElemNumber: 2, qState: 'O' },
              { qText: '37.25', qNum: 37.25, qElemNumber: 0, qState: 'L' },
              { qText: '0.57', qNum: 0.5700000000000001, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'June 2019', qNum: 43617, qElemNumber: 29, qState: 'O' },
              { qText: '48.25', qNum: 48.25, qElemNumber: 0, qState: 'L' },
              { qText: '0.565', qNum: 0.565, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'March 2018', qNum: 43160, qElemNumber: 14, qState: 'O' },
              { qText: '29', qNum: 29, qElemNumber: 0, qState: 'L' },
              { qText: '0.5625', qNum: 0.5625, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'June 2018', qNum: 43252, qElemNumber: 17, qState: 'O' },
              { qText: '27.25', qNum: 27.25, qElemNumber: 0, qState: 'L' },
              { qText: '0.555', qNum: 0.5549999999999999, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'December 2019', qNum: 43800, qElemNumber: 35, qState: 'O' },
              { qText: '45', qNum: 45, qElemNumber: 0, qState: 'L' },
              { qText: '0.55333333', qNum: 0.5533333333333333, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'July 2019', qNum: 43647, qElemNumber: 30, qState: 'O' },
              { qText: '49.5', qNum: 49.5, qElemNumber: 0, qState: 'L' },
              { qText: '0.5525', qNum: 0.5525, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'April 2019', qNum: 43556, qElemNumber: 27, qState: 'O' },
              { qText: '44.75', qNum: 44.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.55', qNum: 0.55, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'May 2019', qNum: 43586, qElemNumber: 28, qState: 'O' },
              { qText: '47.75', qNum: 47.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.5325', qNum: 0.5325, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'November 2017', qNum: 43040, qElemNumber: 10, qState: 'O' },
              { qText: '24', qNum: 24, qElemNumber: 0, qState: 'L' },
              { qText: '0.53', qNum: 0.53, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'November 2019', qNum: 43770, qElemNumber: 34, qState: 'O' },
              { qText: '44.75', qNum: 44.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.52666667', qNum: 0.5266666666666667, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'March 2019', qNum: 43525, qElemNumber: 26, qState: 'O' },
              { qText: '65.333333333333', qNum: 65.33333333333333, qElemNumber: 0, qState: 'L' },
              { qText: '0.52333333', qNum: 0.5233333333333333, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'April 2018', qNum: 43191, qElemNumber: 15, qState: 'O' },
              { qText: '17.666666666667', qNum: 17.666666666666664, qElemNumber: 0, qState: 'L' },
              { qText: '0.52333333', qNum: 0.5233333333333333, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'September 2017', qNum: 42979, qElemNumber: 8, qState: 'O' },
              { qText: '21.5', qNum: 21.5, qElemNumber: 0, qState: 'L' },
              { qText: '0.5225', qNum: 0.5225, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'May 2018', qNum: 43221, qElemNumber: 16, qState: 'O' },
              { qText: '26.25', qNum: 26.25, qElemNumber: 0, qState: 'L' },
              { qText: '0.5075', qNum: 0.5075, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'September 2019', qNum: 43709, qElemNumber: 32, qState: 'O' },
              { qText: '46', qNum: 46, qElemNumber: 0, qState: 'L' },
              { qText: '0.505', qNum: 0.505, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'April 2017', qNum: 42826, qElemNumber: 3, qState: 'O' },
              { qText: '37.75', qNum: 37.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.505', qNum: 0.505, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'June 2017', qNum: 42887, qElemNumber: 5, qState: 'O' },
              { qText: '42.666666666667', qNum: 42.66666666666667, qElemNumber: 0, qState: 'L' },
              { qText: '0.49666667', qNum: 0.4966666666666666, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'October 2017', qNum: 43009, qElemNumber: 9, qState: 'O' },
              { qText: '23.75', qNum: 23.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.495', qNum: 0.49500000000000005, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'July 2017', qNum: 42917, qElemNumber: 6, qState: 'O' },
              { qText: '27', qNum: 27, qElemNumber: 0, qState: 'L' },
              { qText: '0.495', qNum: 0.495, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'October 2019', qNum: 43739, qElemNumber: 33, qState: 'O' },
              { qText: '45.75', qNum: 45.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.4675', qNum: 0.4675, qElemNumber: 0, qState: 'L' },
            ],
            [
              { qText: 'May 2017', qNum: 42856, qElemNumber: 4, qState: 'O' },
              { qText: '38.75', qNum: 38.75, qElemNumber: 0, qState: 'L' },
              { qText: '0.465', qNum: 0.46499999999999997, qElemNumber: 0, qState: 'L' },
            ],
          ],
          qTails: [{ qUp: 0, qDown: 0 }],
          qArea: { qLeft: 0, qTop: 0, qWidth: 3, qHeight: 36 },
        },
      ],
      getEffectiveProperties: {},
    },
  ],
});
