export default {
  DATA: {
    MAIN: 'qHyperCube',
    BIN: 'binData',
  },
  SCALE: {
    COLOR: 'color',
    X: 'x',
    Y: 'y',
    SIZE: 'size',
  },
  COMPONENT: {
    GRID_LINES: 'grid-lines',
    REFERENCE_LINES_X: 'reference-lines-x',
    REFERENCE_LINES_Y: 'reference-lines-y',
    REFERENCE_LINE_LABELS_X: 'reference-line-labels-x',
    REFERENCE_LINE_LABELS_Y: 'reference-line-labels-y',
    POINT: 'point-component',
    POINT_TOOLTIP: 'tooltip',
    POINT_LABELS: 'point-labels',
    LEGEND: 'legend-color',
    LEGEND_CATEGORICAL: 'legend-color-cat',
    LEGEND_CAT_TOOLTIP: 'legend-cat-tooltip',
    X_AXIS: 'x-axis',
    Y_AXIS: 'y-axis',
    X_AXIS_TITLE: 'x-axis-title',
    Y_AXIS_TITLE: 'y-axis-title',
    HEAT_MAP: 'heat-map',
    HEAT_MAP_LABELS: 'heat-map-labels',
    HEAT_MAP_TOOLTIP: 'heat-map-tooltip',
    OUT_OF_BOUNDS: 'out-of-bounds',
  },
  COLLECTION: {
    MAIN: 'main-collection',
  },
  FORMATTER: {
    COLOR: 'color',
    X: 'x',
    Y: 'y',
  },
  FIELDS: {
    DIM: 'qDimensionInfo/0',
    X: 'qMeasureInfo/0',
    Y: 'qMeasureInfo/1',
    SIZE: 'qMeasureInfo/2',
    BIN: 'bin',
    BIN_X: 'binX',
    BIN_Y: 'binY',
    BIN_DENSITY: 'binDensity',
  },
};
