export default {
  AXIS: {
    X: 'SMALL',
    Y: 'XSMALL',
  },
  AXIS_TITLE: {
    X: 'SMALL',
    Y: 'SMALL',
  },
  POINT_LABELS: 'XSMALL',
  HEAT_MAP_LABELS: 'XSMALL',
  GRID_LINES: 'XSMALL',
  REFERENCE_LINES: 'SPARK',
  REFERENCE_LINE_LABELS: 'XSMALL',
  HEAT_MAP_LEGEND: 'MEDIUM',
  MINI_CHART: 'SMALL',
};
